/**
 * i18n data for financeQaoa page.
 * These objects should be appended to src/utils/lang/zh.js and src/utils/lang/en.js.
 * Kept here for reference and preview.
 */
export const zh = {
  financeQaoa: {
    hero: {
      title: '量子组合投资优化',
      subtitle: '基于QAOA量子算法的金融投资组合优化云平台',
    },
    tabs: {
      dashboard: '数据概览',
      statistics: '统计分析',
      classical: '经典优化',
      quantum: '量子优化',
      compare: '对比分析',
    },
    dashboard: {
      tier: '数据层级',
      tierDemo: '演示 (5支)',
      tierStandard: '标准 (8支)',
      tierFull: '完整 (10支)',
      stockCards: '股票概览',
      latestPrice: '最新价',
      totalReturn: '总回报',
      dataPoints: '数据点',
      priceTrend: '价格趋势',
      selectStock: '选择股票',
    },
    statistics: {
      annualReturn: '年化收益率',
      annualVolatility: '年化波动率',
      sharpeRatio: '夏普比率',
      maxDrawdown: '最大回撤',
      totalReturn: '累计回报',
      correlationHeatmap: '相关性热力图',
      riskReturnScatter: '风险-收益散点图',
      statsTable: '统计数据表',
      stock: '股票',
    },
    classical: {
      title: 'Markowitz 均值-方差优化',
      params: '优化参数',
      selectK: '选取股票数 (k)',
      riskAversion: '风险厌恶系数 (q)',
      run: '运行优化',
      running: '优化中...',
      efficientFrontier: '有效前沿',
      weightDistribution: '权重分布',
      selectedStocks: '选中股票',
      portfolioReturn: '组合收益率',
      portfolioRisk: '组合风险',
      portfolioSharpe: '组合夏普比率',
      riskReturnScatter: '风险-收益散点图',
    },
    quantum: {
      title: 'QAOA 量子组合优化',
      params: 'QAOA参数',
      selectK: '选取股票数 (k)',
      riskAversion: '风险厌恶系数 (q)',
      depth: '电路深度 (p)',
      restarts: '随机重启次数',
      forceRerun: '强制重新运行',
      run: '运行QAOA',
      running: 'QAOA优化中...',
      results: '优化结果',
      selectedStocks: '选中股票',
      costGap: '代价差距',
      optimalEnergy: '最优能量',
      nQubits: '量子比特数',
      penaltyWeight: '惩罚权重',
      normFactor: '归一化因子',
      bitstringDistribution: '比特串概率分布',
      weightDistribution: '权重分布',
      bruteForceComparison: '暴力搜索对比',
      portfolioReturn: '组合收益率',
      portfolioRisk: '组合风险',
      portfolioSharpe: '组合夏普比率',
      bruteForceReturn: '暴力搜索收益率',
      bruteForceRisk: '暴力搜索风险',
      bruteForceSharpe: '暴力搜索夏普比率',
    },
    compare: {
      title: '经典 vs 量子对比分析',
      params: '对比参数',
      selectK: '选取股票数 (k)',
      riskAversion: '风险厌恶系数 (q)',
      depth: '电路深度 (p)',
      restarts: '随机重启次数',
      run: '运行对比',
      running: '对比运行中...',
      metricsTable: '性能指标对比',
      method: '方法',
      classicalMethod: '经典Markowitz',
      quantumMethod: 'QAOA量子',
      bruteForceMethod: '暴力搜索',
      portfolioReturn: '组合收益率',
      portfolioRisk: '组合风险',
      portfolioSharpe: '夏普比率',
      costGap: '代价差距',
      selectedStocks: '选中股票',
      weightComparison: '权重对比',
      efficientFrontier: '有效前沿',
      riskReturnChart: '风险-收益对比图',
    },
    message: {
      loadFailed: '数据加载失败',
      networkError: '网络异常，请稍后重试',
      optimizeSuccess: '优化完成',
      optimizeFailed: '优化失败，请重试',
      noData: '暂无数据',
    },
    common: {
      loading: '加载中...',
      retry: '重试',
      percent: '%',
    },
  },
};

export const en = {
  financeQaoa: {
    hero: {
      title: 'Quantum Portfolio Optimization',
      subtitle: 'QAOA-based financial portfolio optimization cloud platform',
    },
    tabs: {
      dashboard: 'Dashboard',
      statistics: 'Statistics',
      classical: 'Classical',
      quantum: 'Quantum',
      compare: 'Compare',
    },
    dashboard: {
      tier: 'Data Tier',
      tierDemo: 'Demo (5 stocks)',
      tierStandard: 'Standard (8 stocks)',
      tierFull: 'Full (10 stocks)',
      stockCards: 'Stock Overview',
      latestPrice: 'Latest Price',
      totalReturn: 'Total Return',
      dataPoints: 'Data Points',
      priceTrend: 'Price Trend',
      selectStock: 'Select Stock',
    },
    statistics: {
      annualReturn: 'Annual Return',
      annualVolatility: 'Annual Volatility',
      sharpeRatio: 'Sharpe Ratio',
      maxDrawdown: 'Max Drawdown',
      totalReturn: 'Total Return',
      correlationHeatmap: 'Correlation Heatmap',
      riskReturnScatter: 'Risk-Return Scatter',
      statsTable: 'Statistics Table',
      stock: 'Stock',
    },
    classical: {
      title: 'Markowitz Mean-Variance Optimization',
      params: 'Optimization Parameters',
      selectK: 'Number of stocks (k)',
      riskAversion: 'Risk aversion (q)',
      run: 'Run Optimization',
      running: 'Optimizing...',
      efficientFrontier: 'Efficient Frontier',
      weightDistribution: 'Weight Distribution',
      selectedStocks: 'Selected Stocks',
      portfolioReturn: 'Portfolio Return',
      portfolioRisk: 'Portfolio Risk',
      portfolioSharpe: 'Portfolio Sharpe',
      riskReturnScatter: 'Risk-Return Scatter',
    },
    quantum: {
      title: 'QAOA Quantum Portfolio Optimization',
      params: 'QAOA Parameters',
      selectK: 'Number of stocks (k)',
      riskAversion: 'Risk aversion (q)',
      depth: 'Circuit depth (p)',
      restarts: 'Random restarts',
      forceRerun: 'Force rerun',
      run: 'Run QAOA',
      running: 'QAOA optimizing...',
      results: 'Optimization Results',
      selectedStocks: 'Selected Stocks',
      costGap: 'Cost Gap',
      optimalEnergy: 'Optimal Energy',
      nQubits: 'Qubits',
      penaltyWeight: 'Penalty Weight',
      normFactor: 'Norm Factor',
      bitstringDistribution: 'Bitstring Probability Distribution',
      weightDistribution: 'Weight Distribution',
      bruteForceComparison: 'Brute Force Comparison',
      portfolioReturn: 'Portfolio Return',
      portfolioRisk: 'Portfolio Risk',
      portfolioSharpe: 'Portfolio Sharpe',
      bruteForceReturn: 'Brute Force Return',
      bruteForceRisk: 'Brute Force Risk',
      bruteForceSharpe: 'Brute Force Sharpe',
    },
    compare: {
      title: 'Classical vs Quantum Comparison',
      params: 'Comparison Parameters',
      selectK: 'Number of stocks (k)',
      riskAversion: 'Risk aversion (q)',
      depth: 'Circuit depth (p)',
      restarts: 'Random restarts',
      run: 'Run Comparison',
      running: 'Comparing...',
      metricsTable: 'Performance Metrics Comparison',
      method: 'Method',
      classicalMethod: 'Classical Markowitz',
      quantumMethod: 'QAOA Quantum',
      bruteForceMethod: 'Brute Force',
      portfolioReturn: 'Portfolio Return',
      portfolioRisk: 'Portfolio Risk',
      portfolioSharpe: 'Sharpe Ratio',
      costGap: 'Cost Gap',
      selectedStocks: 'Selected Stocks',
      weightComparison: 'Weight Comparison',
      efficientFrontier: 'Efficient Frontier',
      riskReturnChart: 'Risk-Return Comparison',
    },
    message: {
      loadFailed: 'Failed to load data',
      networkError: 'Network error. Please try again later.',
      optimizeSuccess: 'Optimization completed',
      optimizeFailed: 'Optimization failed. Please retry.',
      noData: 'No data available',
    },
    common: {
      loading: 'Loading...',
      retry: 'Retry',
      percent: '%',
    },
  },
};
